### ISSUE TITLE
Bug: After latest update crash my templater hotkey event

### ISSUE THREAD

**Issue by cogscides** [joethei/obsidian-key-promoter#10] opened 2022-01-11 20:40 UTC
How I'm using `templater`:
I have template which wrap my text into tag with `tp.file.selection()` and `tp.file.cursor(0)`.
This template assigned to the hotkey through native `templater` settings.

After update of `key-promoter` I faced with issue:
when I select text and use hotkey it broke my line and sent error to the console:
```main.ts:30
Uncaught TypeError: Cannot read property 'id' of undefinedUncaught TypeError: Cannot read property 'id' of undefined
    at t.eval (eval at <anonymous> (app.js:1), <anonymous>:285:83)
    at t.check (eval at <anonymous> (app.js:1), <anonymous>:176:53)
    at t.wrapper (eval at <anonymous> (app.js:1), <anonymous>:155:24)
    at t.eval (eval at <anonymous> (app.js:1), <anonymous>:74:11598)
    at t.o [as executeCommandById] (eval at <anonymous> (app.js:1), <anonymous>:23:77225)
    at t.onTrigger (app.js:1)
    at t.handleKey (app.js:1)
    at t.onKeyEvent (app.js:1)
eval @ main.ts:30
check @ index.js:41
wrapper @ index.js:20
eval @ VM430:74
o @ VM430:23
t.onTrigger @ app.js:1
t.handleKey @ app.js:1
t.onKeyEvent @ app.js:1
```
![image](https://user-images.githubusercontent.com/50235526/149018047-3010dce3-0add-48ec-8e8c-a65b73267c2c.png)

After Disabling `key-promoter` or with using command through `command pallete` all is working good.

**Comment by joethei** [comment] 2022-01-12 16:06
This should be fixed with 1.2.2.
Please let me know as I cannot reproduce this exact issue.

**Closed** 2022-02-18 18:33 UTC
Labels: bug
