### ISSUE TITLE
Export/Printing hotkeys  (newline missing)

### ISSUE THREAD

**Issue by AlanEdd** [joethei/obsidian-key-promoter#14] opened 2024-08-08 14:48 UTC
This would be super for printing hotkeys. I tried the export feature, but it is putting everything in one block of text .
eg:
`
editor:save-file - Save current file - Ctrl + Seditor:follow-link - Follow link under cursor - Alt + Entereditor:open-link-in-new-leaf - Open link under cursor in new tab - Ctrl + Entereditor:open-link-in-new-window - Open link under cursor in new window - Ctrl+Alt+Shift + Enterworkspace:toggle-pin - Toggle pin - No hotkey definededitor:open-link-in-new-split - Open link under cursor to the right - Ctrl+Alt + Entereditor:focus-top - Focus on tab group above - No hotkey definededitor:focus-bottom - Focus on tab group below - No hotkey definededitor:focus-left - Focus on tab group to the left - No hotkey definededitor:focus-right - Focus on tab group to the right - No hotkey definedworkspace:split-vertical - Split righ etc`

Thanks,
Alan.

**Comment by joethei** [comment] 2024-08-08 16:38
Duplicate of #13

**Closed** 2024-08-08 16:39 UTC
